### ISSUE TITLE
Update Cordova from 3.5 to 3.7

### ISSUE THREAD

**Issue by Mike4o** [Icenium/bond-app-template#1]
Since the latest AppBuilder 2.9 release, the default Cordova is now Cordova 3.7 (Android 3.6.4, WP 3.8.0). This goes for the AppBuilder Companion Apps as well, which leads to a warning when the Photo Album app is deployed there. In most of the cases instead of visualizing the actual content of the application there is a white-screen, which is also caused by the difference in the Cordova versions.

For reference, you can check this ticket: https://admin.telerik.com/?Context=Support&Control=~%2fUserControls%2fSupport%2fThreadReply.ascx&ST=932492&SM=0

**Comment by tjvantoll** [comment]
Thanks @Mike4o!

I just pushed an update to address this.
